//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Phim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi_Tiet_Ve
    {
        public long ChiTietVeID { get; set; }
        public long DonDatVeID { get; set; }
        public long LichChieuID { get; set; }
        public long GheID { get; set; }
        public decimal GiaBan { get; set; }
        public Nullable<bool> TrangThaiSuDung { get; set; }
    
        public virtual Don_Dat_Ve Don_Dat_Ve { get; set; }
        public virtual Ghe_Ngoi Ghe_Ngoi { get; set; }
        public virtual Lich_Chieu Lich_Chieu { get; set; }
    }
}
