//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Phim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Don_Dat_Ve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Don_Dat_Ve()
        {
            this.Chi_Tiet_Ve = new HashSet<Chi_Tiet_Ve>();
            this.Lich_Su_Thanh_Toan = new HashSet<Lich_Su_Thanh_Toan>();
        }
    
        public long DonDatVeID { get; set; }
        public string MaDatVe { get; set; }
        public Nullable<long> KhachHangID { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public Nullable<decimal> TongTienDonHang { get; set; }
        public string TrangThaiDonHang { get; set; }
        public Nullable<System.DateTime> ThoiGianDat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_Tiet_Ve> Chi_Tiet_Ve { get; set; }
        public virtual Khach_Hang Khach_Hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lich_Su_Thanh_Toan> Lich_Su_Thanh_Toan { get; set; }
        public virtual User_ User_ { get; set; }
    }
}
