//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Phim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ghe_Ngoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ghe_Ngoi()
        {
            this.Chi_Tiet_Ve = new HashSet<Chi_Tiet_Ve>();
            this.Khoa_Ghe_Tam_Thoi = new HashSet<Khoa_Ghe_Tam_Thoi>();
        }
    
        public long GheID { get; set; }
        public long PhongID { get; set; }
        public string HangGhe { get; set; }
        public int SoGhe { get; set; }
        public string MaGhe { get; set; }
        public string LoaiGhe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_Tiet_Ve> Chi_Tiet_Ve { get; set; }
        public virtual Phong_Chieu Phong_Chieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Khoa_Ghe_Tam_Thoi> Khoa_Ghe_Tam_Thoi { get; set; }
    }
}
