//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Phim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khoa_Ghe_Tam_Thoi
    {
        public long KhoaGheID { get; set; }
        public long LichChieuID { get; set; }
        public long GheID { get; set; }
        public Nullable<long> KhachHangID { get; set; }
        public Nullable<System.DateTime> ThoiGianKhoa { get; set; }
        public System.DateTime ThoiGianHetHan { get; set; }
    
        public virtual Ghe_Ngoi Ghe_Ngoi { get; set; }
        public virtual Khach_Hang Khach_Hang { get; set; }
        public virtual Lich_Chieu Lich_Chieu { get; set; }
    }
}
