//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Phim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lich_Su_Thanh_Toan
    {
        public long ThanhToanID { get; set; }
        public string MaThanhToan { get; set; }
        public long DonDatVeID { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public string MaGiaoDichNganHang { get; set; }
        public decimal SoTienThanhToan { get; set; }
        public Nullable<System.DateTime> ThoiGianThanhToan { get; set; }
        public string TrangThaiThanhToan { get; set; }
    
        public virtual Don_Dat_Ve Don_Dat_Ve { get; set; }
    }
}
