//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Phim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loai_Ve
    {
        public int LoaiVeID { get; set; }
        public string TenLoaiVe { get; set; }
        public Nullable<decimal> TiLeGia { get; set; }
    }
}
