            //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

        namespace Web_Phim.Models
    {
        using System;
        using System.Data.Entity;
        using System.Data.Entity.Infrastructure;
            using System.Data.Entity.Core.Objects;
        using System.Linq;
        
        public partial class LTW_DatVeXemPhimEntities : DbContext
        {
            public LTW_DatVeXemPhimEntities()
                : base("name=LTW_DatVeXemPhimEntities")
            {
                }
    
            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                throw new UnintentionalCodeFirstException();
            }
    
                public virtual DbSet<Chi_Tiet_Ve> Chi_Tiet_Ve { get; set; }
                public virtual DbSet<Don_Dat_Ve> Don_Dat_Ve { get; set; }
                public virtual DbSet<Ghe_Ngoi> Ghe_Ngoi { get; set; }
                public virtual DbSet<Khach_Hang> Khach_Hang { get; set; }
                public virtual DbSet<Khoa_Ghe_Tam_Thoi> Khoa_Ghe_Tam_Thoi { get; set; }
                public virtual DbSet<Lich_Chieu> Lich_Chieu { get; set; }
                public virtual DbSet<Lich_Su_Thanh_Toan> Lich_Su_Thanh_Toan { get; set; }
                public virtual DbSet<Loai_Ve> Loai_Ve { get; set; }
                public virtual DbSet<NhatKyHoatDong> NhatKyHoatDongs { get; set; }
                public virtual DbSet<Phim> Phims { get; set; }
                public virtual DbSet<Phong_Chieu> Phong_Chieu { get; set; }
                public virtual DbSet<Rap_Chieu> Rap_Chieu { get; set; }
                public virtual DbSet<TheLoai> TheLoais { get; set; }
                public virtual DbSet<User_> User_ { get; set; }
                public virtual DbSet<UserGroup> UserGroups { get; set; }
        
            public virtual ObjectResult<sp_BaoCaoChiTieuKhachHangg_Cursor_Result> sp_BaoCaoChiTieuKhachHangg_Cursor()
            {
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BaoCaoChiTieuKhachHangg_Cursor_Result>("sp_BaoCaoChiTieuKhachHangg_Cursor");
            }
        
            public virtual int sp_DangKyKhachHang(string userName, string password, string hoTen, string email, string soDienThoai)
            {
                    var userNameParameter = userName != null ?
                    new ObjectParameter("UserName", userName) :
                    new ObjectParameter("UserName", typeof(string));
    
                    var passwordParameter = password != null ?
                    new ObjectParameter("Password", password) :
                    new ObjectParameter("Password", typeof(string));
    
                    var hoTenParameter = hoTen != null ?
                    new ObjectParameter("HoTen", hoTen) :
                    new ObjectParameter("HoTen", typeof(string));
    
                    var emailParameter = email != null ?
                    new ObjectParameter("Email", email) :
                    new ObjectParameter("Email", typeof(string));
    
                    var soDienThoaiParameter = soDienThoai != null ?
                    new ObjectParameter("SoDienThoai", soDienThoai) :
                    new ObjectParameter("SoDienThoai", typeof(string));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DangKyKhachHang", userNameParameter, passwordParameter, hoTenParameter, emailParameter, soDienThoaiParameter);
            }
        
            public virtual ObjectResult<sp_DatVePhim_Result> sp_DatVePhim(Nullable<long> khachHangID, Nullable<long> lichChieuID, string danhSachGheID, Nullable<int> nhanVienID)
            {
                    var khachHangIDParameter = khachHangID.HasValue ?
                    new ObjectParameter("KhachHangID", khachHangID) :
                    new ObjectParameter("KhachHangID", typeof(long));
    
                    var lichChieuIDParameter = lichChieuID.HasValue ?
                    new ObjectParameter("LichChieuID", lichChieuID) :
                    new ObjectParameter("LichChieuID", typeof(long));
    
                    var danhSachGheIDParameter = danhSachGheID != null ?
                    new ObjectParameter("DanhSachGheID", danhSachGheID) :
                    new ObjectParameter("DanhSachGheID", typeof(string));
    
                    var nhanVienIDParameter = nhanVienID.HasValue ?
                    new ObjectParameter("NhanVienID", nhanVienID) :
                    new ObjectParameter("NhanVienID", typeof(int));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DatVePhim_Result>("sp_DatVePhim", khachHangIDParameter, lichChieuIDParameter, danhSachGheIDParameter, nhanVienIDParameter);
            }
        
            public virtual int sp_DoiMatKhauCaNhann(Nullable<int> userID, string matKhauCu, string matKhauMoi)
            {
                    var userIDParameter = userID.HasValue ?
                    new ObjectParameter("UserID", userID) :
                    new ObjectParameter("UserID", typeof(int));
    
                    var matKhauCuParameter = matKhauCu != null ?
                    new ObjectParameter("MatKhauCu", matKhauCu) :
                    new ObjectParameter("MatKhauCu", typeof(string));
    
                    var matKhauMoiParameter = matKhauMoi != null ?
                    new ObjectParameter("MatKhauMoi", matKhauMoi) :
                    new ObjectParameter("MatKhauMoi", typeof(string));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DoiMatKhauCaNhann", userIDParameter, matKhauCuParameter, matKhauMoiParameter);
            }
        
            public virtual int sp_KhoaGheDeThanhToan(Nullable<long> lichChieuID, Nullable<int> userID, string listGheID)
            {
                    var lichChieuIDParameter = lichChieuID.HasValue ?
                    new ObjectParameter("LichChieuID", lichChieuID) :
                    new ObjectParameter("LichChieuID", typeof(long));
    
                    var userIDParameter = userID.HasValue ?
                    new ObjectParameter("UserID", userID) :
                    new ObjectParameter("UserID", typeof(int));
    
                    var listGheIDParameter = listGheID != null ?
                    new ObjectParameter("ListGheID", listGheID) :
                    new ObjectParameter("ListGheID", typeof(string));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_KhoaGheDeThanhToan", lichChieuIDParameter, userIDParameter, listGheIDParameter);
            }
        
            public virtual ObjectResult<sp_KiemTraDangNhap_Result> sp_KiemTraDangNhap(string userName, string password)
            {
                    var userNameParameter = userName != null ?
                    new ObjectParameter("UserName", userName) :
                    new ObjectParameter("UserName", typeof(string));
    
                    var passwordParameter = password != null ?
                    new ObjectParameter("Password", password) :
                    new ObjectParameter("Password", typeof(string));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_KiemTraDangNhap_Result>("sp_KiemTraDangNhap", userNameParameter, passwordParameter);
            }
        
            public virtual ObjectResult<sp_LayDanhSachChiTietNguoiDung_Result> sp_LayDanhSachChiTietNguoiDung()
            {
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDanhSachChiTietNguoiDung_Result>("sp_LayDanhSachChiTietNguoiDung");
            }
        
            public virtual ObjectResult<sp_LayDanhSachGheVoiTrangThai_Result> sp_LayDanhSachGheVoiTrangThai(Nullable<long> lichChieuID)
            {
                    var lichChieuIDParameter = lichChieuID.HasValue ?
                    new ObjectParameter("LichChieuID", lichChieuID) :
                    new ObjectParameter("LichChieuID", typeof(long));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDanhSachGheVoiTrangThai_Result>("sp_LayDanhSachGheVoiTrangThai", lichChieuIDParameter);
            }
        
            public virtual ObjectResult<sp_LayDanhSachGiaVeTheoLichChieu_Result> sp_LayDanhSachGiaVeTheoLichChieu(Nullable<long> lichChieuID)
            {
                    var lichChieuIDParameter = lichChieuID.HasValue ?
                    new ObjectParameter("LichChieuID", lichChieuID) :
                    new ObjectParameter("LichChieuID", typeof(long));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDanhSachGiaVeTheoLichChieu_Result>("sp_LayDanhSachGiaVeTheoLichChieu", lichChieuIDParameter);
            }
        
            public virtual ObjectResult<sp_LayLichChieuTheoPhim_Result> sp_LayLichChieuTheoPhim(Nullable<long> phimID)
            {
                    var phimIDParameter = phimID.HasValue ?
                    new ObjectParameter("PhimID", phimID) :
                    new ObjectParameter("PhimID", typeof(long));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayLichChieuTheoPhim_Result>("sp_LayLichChieuTheoPhim", phimIDParameter);
            }
        
            public virtual ObjectResult<sp_LayLichSuDatVeChiTiet_Result> sp_LayLichSuDatVeChiTiet(Nullable<int> userID)
            {
                    var userIDParameter = userID.HasValue ?
                    new ObjectParameter("UserID", userID) :
                    new ObjectParameter("UserID", typeof(int));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayLichSuDatVeChiTiet_Result>("sp_LayLichSuDatVeChiTiet", userIDParameter);
            }
        
            public virtual ObjectResult<sp_LayThongTinTomTatBooking_Result> sp_LayThongTinTomTatBooking(Nullable<long> lichChieuID)
            {
                    var lichChieuIDParameter = lichChieuID.HasValue ?
                    new ObjectParameter("LichChieuID", lichChieuID) :
                    new ObjectParameter("LichChieuID", typeof(long));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayThongTinTomTatBooking_Result>("sp_LayThongTinTomTatBooking", lichChieuIDParameter);
            }
        
            public virtual int sp_PhanLoaiKhachHang_Cursor()
            {
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PhanLoaiKhachHang_Cursor");
            }
        
            public virtual int sp_PhanLoaiPhim_DoanhThu_Cursor()
            {
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PhanLoaiPhim_DoanhThu_Cursor");
            }
        
            public virtual int sp_SuaPhim(Nullable<long> phimID, string tenPhim, string moTa, string daoDien, Nullable<System.DateTime> ngayKhoiChieu, Nullable<int> thoiLuong, string phanLoaiDoTuoi, string poster, Nullable<int> maTheLoai)
            {
                    var phimIDParameter = phimID.HasValue ?
                    new ObjectParameter("PhimID", phimID) :
                    new ObjectParameter("PhimID", typeof(long));
    
                    var tenPhimParameter = tenPhim != null ?
                    new ObjectParameter("TenPhim", tenPhim) :
                    new ObjectParameter("TenPhim", typeof(string));
    
                    var moTaParameter = moTa != null ?
                    new ObjectParameter("MoTa", moTa) :
                    new ObjectParameter("MoTa", typeof(string));
    
                    var daoDienParameter = daoDien != null ?
                    new ObjectParameter("DaoDien", daoDien) :
                    new ObjectParameter("DaoDien", typeof(string));
    
                    var ngayKhoiChieuParameter = ngayKhoiChieu.HasValue ?
                    new ObjectParameter("NgayKhoiChieu", ngayKhoiChieu) :
                    new ObjectParameter("NgayKhoiChieu", typeof(System.DateTime));
    
                    var thoiLuongParameter = thoiLuong.HasValue ?
                    new ObjectParameter("ThoiLuong", thoiLuong) :
                    new ObjectParameter("ThoiLuong", typeof(int));
    
                    var phanLoaiDoTuoiParameter = phanLoaiDoTuoi != null ?
                    new ObjectParameter("PhanLoaiDoTuoi", phanLoaiDoTuoi) :
                    new ObjectParameter("PhanLoaiDoTuoi", typeof(string));
    
                    var posterParameter = poster != null ?
                    new ObjectParameter("Poster", poster) :
                    new ObjectParameter("Poster", typeof(string));
    
                    var maTheLoaiParameter = maTheLoai.HasValue ?
                    new ObjectParameter("MaTheLoai", maTheLoai) :
                    new ObjectParameter("MaTheLoai", typeof(int));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaPhim", phimIDParameter, tenPhimParameter, moTaParameter, daoDienParameter, ngayKhoiChieuParameter, thoiLuongParameter, phanLoaiDoTuoiParameter, posterParameter, maTheLoaiParameter);
            }
        
            public virtual ObjectResult<Nullable<long>> sp_ThanhToanVaDatVe(Nullable<int> userID, Nullable<long> lichChieuID, string listGheID, Nullable<decimal> tongTien, string phuongThucThanhToan)
            {
                    var userIDParameter = userID.HasValue ?
                    new ObjectParameter("UserID", userID) :
                    new ObjectParameter("UserID", typeof(int));
    
                    var lichChieuIDParameter = lichChieuID.HasValue ?
                    new ObjectParameter("LichChieuID", lichChieuID) :
                    new ObjectParameter("LichChieuID", typeof(long));
    
                    var listGheIDParameter = listGheID != null ?
                    new ObjectParameter("ListGheID", listGheID) :
                    new ObjectParameter("ListGheID", typeof(string));
    
                    var tongTienParameter = tongTien.HasValue ?
                    new ObjectParameter("TongTien", tongTien) :
                    new ObjectParameter("TongTien", typeof(decimal));
    
                    var phuongThucThanhToanParameter = phuongThucThanhToan != null ?
                    new ObjectParameter("PhuongThucThanhToan", phuongThucThanhToan) :
                    new ObjectParameter("PhuongThucThanhToan", typeof(string));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("sp_ThanhToanVaDatVe", userIDParameter, lichChieuIDParameter, listGheIDParameter, tongTienParameter, phuongThucThanhToanParameter);
            }
        
            public virtual ObjectResult<sp_ThemLichChieu_Transaction_Result> sp_ThemLichChieu_Transaction(Nullable<long> phimID, Nullable<long> phongID, Nullable<System.DateTime> thoiGianBatDau, Nullable<decimal> giaVe, string dinhDang)
            {
                    var phimIDParameter = phimID.HasValue ?
                    new ObjectParameter("PhimID", phimID) :
                    new ObjectParameter("PhimID", typeof(long));
    
                    var phongIDParameter = phongID.HasValue ?
                    new ObjectParameter("PhongID", phongID) :
                    new ObjectParameter("PhongID", typeof(long));
    
                    var thoiGianBatDauParameter = thoiGianBatDau.HasValue ?
                    new ObjectParameter("ThoiGianBatDau", thoiGianBatDau) :
                    new ObjectParameter("ThoiGianBatDau", typeof(System.DateTime));
    
                    var giaVeParameter = giaVe.HasValue ?
                    new ObjectParameter("GiaVe", giaVe) :
                    new ObjectParameter("GiaVe", typeof(decimal));
    
                    var dinhDangParameter = dinhDang != null ?
                    new ObjectParameter("DinhDang", dinhDang) :
                    new ObjectParameter("DinhDang", typeof(string));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThemLichChieu_Transaction_Result>("sp_ThemLichChieu_Transaction", phimIDParameter, phongIDParameter, thoiGianBatDauParameter, giaVeParameter, dinhDangParameter);
            }
        
            public virtual ObjectResult<sp_ThemNhanVien_Result> sp_ThemNhanVien(string userName, string password, string hoTen, string email, string soDienThoai, Nullable<int> groupID)
            {
                    var userNameParameter = userName != null ?
                    new ObjectParameter("UserName", userName) :
                    new ObjectParameter("UserName", typeof(string));
    
                    var passwordParameter = password != null ?
                    new ObjectParameter("Password", password) :
                    new ObjectParameter("Password", typeof(string));
    
                    var hoTenParameter = hoTen != null ?
                    new ObjectParameter("HoTen", hoTen) :
                    new ObjectParameter("HoTen", typeof(string));
    
                    var emailParameter = email != null ?
                    new ObjectParameter("Email", email) :
                    new ObjectParameter("Email", typeof(string));
    
                    var soDienThoaiParameter = soDienThoai != null ?
                    new ObjectParameter("SoDienThoai", soDienThoai) :
                    new ObjectParameter("SoDienThoai", typeof(string));
    
                    var groupIDParameter = groupID.HasValue ?
                    new ObjectParameter("GroupID", groupID) :
                    new ObjectParameter("GroupID", typeof(int));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThemNhanVien_Result>("sp_ThemNhanVien", userNameParameter, passwordParameter, hoTenParameter, emailParameter, soDienThoaiParameter, groupIDParameter);
            }
        
            public virtual int sp_ThemPhim(string tenPhim, string moTa, string daoDien, Nullable<int> maTheLoai, Nullable<int> thoiLuong, string poster, string trangThai, string phanLoaiDoTuoi, Nullable<System.DateTime> ngayKhoiChieu)
            {
                    var tenPhimParameter = tenPhim != null ?
                    new ObjectParameter("TenPhim", tenPhim) :
                    new ObjectParameter("TenPhim", typeof(string));
    
                    var moTaParameter = moTa != null ?
                    new ObjectParameter("MoTa", moTa) :
                    new ObjectParameter("MoTa", typeof(string));
    
                    var daoDienParameter = daoDien != null ?
                    new ObjectParameter("DaoDien", daoDien) :
                    new ObjectParameter("DaoDien", typeof(string));
    
                    var maTheLoaiParameter = maTheLoai.HasValue ?
                    new ObjectParameter("MaTheLoai", maTheLoai) :
                    new ObjectParameter("MaTheLoai", typeof(int));
    
                    var thoiLuongParameter = thoiLuong.HasValue ?
                    new ObjectParameter("ThoiLuong", thoiLuong) :
                    new ObjectParameter("ThoiLuong", typeof(int));
    
                    var posterParameter = poster != null ?
                    new ObjectParameter("Poster", poster) :
                    new ObjectParameter("Poster", typeof(string));
    
                    var trangThaiParameter = trangThai != null ?
                    new ObjectParameter("TrangThai", trangThai) :
                    new ObjectParameter("TrangThai", typeof(string));
    
                    var phanLoaiDoTuoiParameter = phanLoaiDoTuoi != null ?
                    new ObjectParameter("PhanLoaiDoTuoi", phanLoaiDoTuoi) :
                    new ObjectParameter("PhanLoaiDoTuoi", typeof(string));
    
                    var ngayKhoiChieuParameter = ngayKhoiChieu.HasValue ?
                    new ObjectParameter("NgayKhoiChieu", ngayKhoiChieu) :
                    new ObjectParameter("NgayKhoiChieu", typeof(System.DateTime));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemPhim", tenPhimParameter, moTaParameter, daoDienParameter, maTheLoaiParameter, thoiLuongParameter, posterParameter, trangThaiParameter, phanLoaiDoTuoiParameter, ngayKhoiChieuParameter);
            }
        
            public virtual ObjectResult<sp_ThongKeNguoiDungTheoQuyen_Result> sp_ThongKeNguoiDungTheoQuyen()
            {
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeNguoiDungTheoQuyen_Result>("sp_ThongKeNguoiDungTheoQuyen");
            }
        
            public virtual ObjectResult<sp_XoaMemPhim_Transaction_Result> sp_XoaMemPhim_Transaction(Nullable<long> phimID)
            {
                    var phimIDParameter = phimID.HasValue ?
                    new ObjectParameter("PhimID", phimID) :
                    new ObjectParameter("PhimID", typeof(long));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XoaMemPhim_Transaction_Result>("sp_XoaMemPhim_Transaction", phimIDParameter);
            }
        
            public virtual ObjectResult<sp_XoaNguoiDung_Result> sp_XoaNguoiDung(Nullable<int> userID)
            {
                    var userIDParameter = userID.HasValue ?
                    new ObjectParameter("UserID", userID) :
                    new ObjectParameter("UserID", typeof(int));
    
                    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XoaNguoiDung_Result>("sp_XoaNguoiDung", userIDParameter);
            }
            }
            }
        