//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Phim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.Lich_Chieu = new HashSet<Lich_Chieu>();
        }
    
        public long PhimID { get; set; }
        public string MaPhim { get; set; }
        public string TenPhim { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayKhoiChieu { get; set; }
        public int ThoiLuong { get; set; }
        public string DaoDien { get; set; }
        public string PhanLoaiDoTuoi { get; set; }
        public string Poster { get; set; }
        public string TrangThai { get; set; }
        public int MaTheLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lich_Chieu> Lich_Chieu { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
