//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Phim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong_Chieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong_Chieu()
        {
            this.Ghe_Ngoi = new HashSet<Ghe_Ngoi>();
            this.Lich_Chieu = new HashSet<Lich_Chieu>();
        }
    
        public long PhongID { get; set; }
        public string MaPhong { get; set; }
        public long RapID { get; set; }
        public string TenPhong { get; set; }
        public string LoaiPhong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ghe_Ngoi> Ghe_Ngoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lich_Chieu> Lich_Chieu { get; set; }
        public virtual Rap_Chieu Rap_Chieu { get; set; }
    }
}
