//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Phim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rap_Chieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rap_Chieu()
        {
            this.Phong_Chieu = new HashSet<Phong_Chieu>();
        }
    
        public long RapID { get; set; }
        public string MaRap { get; set; }
        public string TenRap { get; set; }
        public string DiaChi { get; set; }
        public string ThanhPho { get; set; }
        public string SoDienThoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phong_Chieu> Phong_Chieu { get; set; }
    }
}
